# Generated by Django 4.1.7 on 2023-04-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebTest', '0003_alter_result_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_test',
            name='cover',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
